AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Root stack
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR
          - EdgeSubnet1CIDR
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
      EdgeSubnet1CIDR:
        default: Edge Subnet 1
      OAMSubnet1CIDR:
        default: OAM Subnet 1
Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.0.0/16
    Description: CIDR block for the VPC
    Type: String
  EdgeSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.63.0/27
    Description: CIDR block for edge subnet 1 located in Availability Zone 1
    Type: String
  OAMSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.32.0/21
    Description: CIDR block for OAM Subnet 1
    Type: String
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://adminip-dev-cfntemplates-bucket.s3-eu-west-1.amazonaws.com/infrastructure/adminip-dev-vpc-stack.yaml
      Parameters:
        VPCCIDR: !Ref VPCCIDR
  SubnetStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://adminip-dev-cfntemplates-bucket.s3-eu-west-1.amazonaws.com/infrastructure/adminip-dev-subnet-stack.yaml
      Parameters:
        EdgeSubnet1CIDR: !Ref EdgeSubnet1CIDR
        OAMSubnet1CIDR: !Ref OAMSubnet1CIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
  RouteTableStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://adminip-dev-cfntemplates-bucket.s3-eu-west-1.amazonaws.com/infrastructure/adminip-dev-routetable-stack.yaml
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        EdgeSubnet1ID: !GetAtt SubnetStack.Outputs.EdgeSubnet1ID
        OAMSubnet1ID: !GetAtt SubnetStack.Outputs.OAMSubnet1ID
