AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Nested Network Stack for Subnets
Parameters:
  EdgeSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.63.0/27
    Description: CIDR block for Edge Subnet 1
    Type: String
  OAMSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.32.0/21
    Description: CIDR block for OAM Subnet 1
    Type: String
  VPCID:
    Description: VPCStack VPC ID
    Type: String
Resources:
  EdgeSubnet1:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Retain
    Properties:
      VpcId: !Ref 'VPCID'
      CidrBlock: !Ref 'EdgeSubnet1CIDR'
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: adminip-dev-edge-e-1-pri-net
  OAMSubnet1:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Retain
    Properties:
      VpcId: !Ref 'VPCID'
      CidrBlock: !Ref 'OAMSubnet1CIDR'
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:
      - Key: Name
        Value: adminip-dev-srvoam-o-1-pri-net
Outputs:
  EdgeSubnet1ID:
    Value:
      Ref: EdgeSubnet1
    Description: Edge Subnet 1 ID
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EdgeSubnet1"
  OAMSubnet1ID:
    Value:
      Ref: OAMSubnet1
    Description: OAM Subnet 1 ID
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-OAMSubnet1"
