AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Nested Network Stack for Subnets
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - EdgeSubnet1CIDR
          - VPCID
    ParameterLabels:
      EdgeSubnet1CIDR:
        default: Edge Subnet 1 CIDR
      VPCID:
        default: VPC Stack VPC ID
Parameters:
  EdgeSubnet1CIDR:
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.12.0/24
    Description: CIDR block for Edge Subnet 1
    Type: String
  VPCID:
    Description: VPCStack VPC ID
    Type: String
Resources:
  NetStack:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPCID'
      CidrBlock: !Ref 'EdgeSubnet1CIDR'
      AvailabilityZone: !Select [ 0, !GetAZs ]
      Tags:  
      - Key: Name
        Value: adminip-dev-edge-e-1-pri-net
Outputs:
  EdgeSubnet1CIDR:
    Value:
      Ref: EdgeSubnet1CIDR
    Description: Edge Subnet 1 CIDR
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EdgeSubnet1CIDR"