AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Root stack for Admin
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR
          - EdgeSubnet1CIDR
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
      EdgeSubnet1CIDR:
        default: Edge Subnet 1
Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.0.0/16
    Description: CIDR block for the VPC
    Type: String
  EdgeSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.97.12.0/24
    Description: CIDR block for edge subnet 1 located in Availability Zone 1
    Type: String
Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub >-
        https://cfnbucketfileslab.s3-eu-west-1.amazonaws.com/vpc-stack.yml
      Parameters:
        VPCCIDR: !Ref VPCCIDR
  NetStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub >-
        https://cfnbucketfileslab.s3-eu-west-1.amazonaws.com/net-stack.yml
      Parameters:
        EdgeSubnet1CIDR: !Ref EdgeSubnet1CIDR
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
Outputs:
  VPCCIDR:
    Value:
      Ref: VPCCIDR
    Description: VPCCIDR
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-VPCCIDR"
  EdgeSubnet1CIDR:
    Value:
      Ref: EdgeSubnet1CIDR
    Description: EdgeSubnet1CIDR
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-EdgeSubnet1CIDR"
