AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation to create internet gateway and NAT gateway in DMZ subnet
Parameters:
  VPCID:
    Description: VPCStack VPC ID
    Type: String
  DMZSubnet1ID:
    Description: DMZ Subnet 1 ID
    Type: String
  DMZSubnet2ID:
    Description: DMZ Subnet 2 ID
    Type: String
#  DMZSubnet3ID:
#    Description: DMZ Subnet 3 ID
#    Type: String
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: adminip-dev-internet-igw
  InternetGatewayAtt:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCID
  NatGatewayEip1:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAtt
    Properties:
      Domain: vpc
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEip1.AllocationId
      SubnetId: !Ref DMZSubnet1ID
  NatGatewayEip2:
    Type: AWS::EC2::EIP
    DependsOn: InternetGatewayAtt
    Properties:
      Domain: vpc
  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEip2.AllocationId
      SubnetId: !Ref DMZSubnet2ID
#  NatGatewayEip3:
#    Type: AWS::EC2::EIP
#    DependsOn: InternetGatewayAtt
#    Properties:
#      Domain: vpc
#  NatGateway3:
#    Type: AWS::EC2::NatGateway
#    Properties:
#      AllocationId: !GetAtt NatGatewayEip3.AllocationId
#      SubnetId: !Ref DMZSubnet3ID
Outputs:
  InternetGatewayID:
    Value: !Ref InternetGateway
    Description: Internet Gateway ID
    Export:
      Name: !Sub "${AWS::StackName}-InternetGateway"
  NatGateway1ID:
    Value: !Ref NatGateway1
    Description: Nat Gateway 1 ID
    Export:
      Name: !Sub "${AWS::StackName}-NatGateway1"
  NatGateway2ID:
    Value: !Ref NatGateway2
    Description: Nat Gateway 2 ID
    Export:
      Name: !Sub "${AWS::StackName}-NatGateway2"
#  NatGateway3ID:
#    Value: !Ref NatGateway3
#    Description: Nat Gateway 3 ID
#    Export:
#      Name: !Sub "${AWS::StackName}-NatGateway3"
